---
debug: 0
check_interval: 60
log: /var/log/heating.log
min_time: 1800
min_temp: 24.0
kill_temp: 30.0
switches:
    heating_pump: http://10.2.2.195/arduino/digital/6
    underfloor_pump: http://10.2.2.195/arduino/digital/7
manual_override:
    file: /tmp/temp_override
    duration: 7200
sensors:
    kitchen:
        url: http://10.2.2.195/arduino/digital/8
        min_temp:  24.9
        max_temp:  25.8
        kill_temp: 28
        start_time: 8:00
        stop_time:  20:00
        js_log: 1
        js_file: /var/www/html/js/out_stats.js
    livingroom:
        url: http://10.2.2.246/temp.py
        min_temp:  24.9
        max_temp:  25.8
        kill_temp: 26.0
        start_time: 8:00
        stop_time:  20:00
        js_log: 0
        js_file: /var/www/html/js/livingrootm_stats.js
    bedroom:
        url: http://10.2.2.245/temp.py
        min_temp:  24.5
        max_temp:  25.2
        kill_temp: 26.0
        start_time: 19:00
        stop_time:  10:00
        js_log: 0
        js_file: /var/www/html/js/bedroom_stats.js
